[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
arbitrum_one = "https://arb1.arbitrum.io/rpc"

# [etherscan]
# arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }
# arbitrum_one = { key = "${ARBISCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

